language: generic
sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tfurnell/multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tfurnell/multi-docker-react-test npm run test -- --coverage

after_success:
  - docker build -t tfurnell/multi-client ./client
  - docker build -t tfurnell/multi-nginx ./nginx
  - docker build -t tfurnell/multi-server ./server
  - docker build -t tfurnell/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tfurnell/multi-client
  - docker push tfurnell/multi-nginx
  - docker push tfurnell/multi-server
  - docker push tfurnell/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: Multidocker-env-1
  bucket_name: elasticbeanstalk-eu-west-1-230003386687
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY